name: LINE CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'bot/line/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: launchpencil
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/zikanwari/zikanwari
      - uses: docker/build-push-action@v2
        with:
          context: bot/line
          push: true
          tags: ghcr.io/zikanwari/zikanwari:line