name: LINE CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'bot/line/**'

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # 4. Login DockerHub
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: zikanwari
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: meta
      id: meta
      uses: docker/metadata-action@v3
      with:
          images: ghcr.io/zikanwari/zikanwari
    # 5. setup buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: bot/line
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/zikanwari/zikanwari:line
